language: java
sudo: false
install: true

addons:
  sonarqube: true

env:
  global:
    - secure: "e96862a3f4eb71062d648c1e9d22ccdc8b342e7b"

jdk:
  - oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.login=$SONAR_TOKEN

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
