language: java
sudo: false
install: true

mvn sonar:sonar \
  -Dsonar.organization=easfilho-github \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=9e8facc208af20cde90eaf10544d54d293dae145


jdk:
  - oraclejdk8

script:
  - mvn clean verify

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
