language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "sonarcloud"
    token:
      secure: "e96862a3f4eb71062d648c1e9d22ccdc8b342e7b"


jdk:
  - oraclejdk8

script:
  - mvn clean verify sonar-scanner

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
