language: java
sudo: false
dist: trusty
addons:
  sonarcloud:
    token:
      secure: ab085de1535abc5290210c31884eca8a8f835c34 # encrypted value of your token
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar \
  -Dsonar.organization=easfilho-github \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=ab085de1535abc5290210c31884eca8a8f835c34
